### ISSUE TITLE
Unable to use pmem-redis with Redis 5.0

### ISSUE THREAD

**Issue by jithutho** [pmem/pmem-redis#7]
Had been trying to use pmem-redis with Redis 5.0.
Building the two together fails due to difference in the jemalloc library being used in pmem-redis and redis 5.0.

On executing, "make USE_NVM=yes" the following error in thrown on Ubuntu 16.04.
--===============
../redis-5.0/deps'
    CC adlist.o
    CC quicklist.o
In file included from ../deps/memkind/include/memkind/internal/memkind_pmem.h:32:0,
                 from nvm.h:37,
                 from quicklist.c:43:
../deps/memkind/include/memkind/internal/memkind_arena.h:44:52: error: unknown type name ‘chunk_hooks_t’
 int memkind_arena_create_map(struct memkind *kind, chunk_hooks_t *hooks);
                                                    ^
Makefile:299: recipe for target 'quicklist.o' failed
make[1]: *** [quicklist.o] Error 1
--===============

The issue seems to be due to change in the jemalloc implementation in jemalloc 5.0 which is being used by Redis 5.0.

Would like to know,
1). whether pmem-redis has been tried with jemalloc 5.0 as I see one comment with respect to jemallocat library not working with jemalloc 5.0 (https://github.com/pmem/pmem-redis/commit/2ea9574e0a1aac8b8fdc75fe16a4e0c3c1ec1f9e)
2). whether any workaround available so that pmem-redis works with redis 5.0
3). whether any roadmap is available for moving pmem-redis to redis 5.0

Would like to have your inputs and suggestions on this issue.

**Comment by KVKIT** [comment]
Yes, current implementation has a hard depend on the jemalloc v4.0. We have no plan to support new version of jemalloc, sorry for it.
